from discord.ext import commands
from strawpoll import API, Poll, ExistingPoll, HTTPException, StrawpollException


class Web(commands.Cog):
    """
    This contains various commands for interacting wit web-based services.
    """

    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def poll(self, ctx: commands.Context, *args):
        """
        Creates a strawpoll from the arguments.
        :param ctx: Context of the message. This parameter is autogenerated.
        :param args: Arguments from which the poll is created.
                     Note: Multi-word arguments have to be quoted.
                     Example: !poll "Is this command great?" Yes No
        :return: URL of the poll
        """
        if args.__len__() < 3 or args[0].__len__() == 0 or args[1].__len__() == 0 or args[2].__len__() == 0:
            #  check if there are enough arguments
            await ctx.send("Please specify at least a title and two options.")
            return
        api: API = API()
        poll: Poll = Poll(args[0], args[1:])
        try:
            poll = await api.submit_poll(poll=poll)
            # If this fails with a type error, this is most probably because strawpoll,py does not yet (April 2019) use
            # https which is required by strawpoll.me since February 2018. For a fix use this commit:
            # https://github.com/PapyrusThePlant/strawpoll.py/pull/5
            # TODO: Include a fixed api.py in this project, so that this error does not happen.
        except StrawpollException as se:
            if isinstance(se, ExistingPoll):
                await ctx.send("Error: This poll already exists.")
            elif isinstance(se, HTTPException):
                await ctx.send("HTTP Error " + se.code + ": " + se.text)
            else:
                await ctx.send("An error occurred:\n" + se.__str__())
            return
        except TypeError as te:
            await ctx.send("Type Error. This most likely happened because of using a version of strawpoll.py which "
                           "does not use https. Please tell the person hosting this bot to take a look at "
                           "https://github.com/PapyrusThePlant/strawpoll.py/pull/5")
            print(te)
            print("Type Error. This most likely happened because of using a version of strawpoll.py which "
                  "does not use https. Please take a look at https://github.com/PapyrusThePlant/strawpoll.py/pull/5")
            return
        await ctx.send("Here is your poll:\n" + poll.url)


def setup(bot):
    bot.add_cog(Web(bot))
    # Adds the web commands to the bot
